ERROR!!! Firebase Implementation
To add Firebase SDK in project, I declared dependencies ini the build.gradle at lvl of project and app, but in the syncronitation this error appears:

Build was configured to prefer settings repositories over project repositories but repository 'Google' was added by build file 'build.gradle'

org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'PayanMapsPrototipe'.

Caused by: org.gradle.api.InvalidUserCodeException: Build was configured to prefer settings repositories over project repositories but repository 'Google' was added by build file 'build.gradle'